# Generated by Django 5.2 on 2025-10-15 13:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_alter_product_datetime_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('np', 'Not Paid'), ('rg', 'Registered'), ('po', 'Posted'), ('de', 'Delivered'), ('ex', 'Expired'), ('ca', 'Canceled'), ('rt', 'Returned')], default='np', max_length=2, verbose_name='Order Status')),
                ('phone_number', models.CharField(error_messages={'unique': 'This phone number has been registered before'}, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid_phone_number', message='Phone number has to be 11 digits exactly', regex='^[0-10]{11}$')], verbose_name='Phone Number(IR)')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('address', models.CharField(max_length=700, verbose_name='Full Address')),
                ('note', models.TextField(blank=True, verbose_name='Extra Note')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Order Added At')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Order Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='Product')),
            ],
        ),
    ]
