# Generated by Django 5.2 on 2025-10-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Phone Number(IR)'),
        ),
    ]
