# Generated by Django 5.2 on 2025-10-18 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_shipment',
            field=models.DateField(choices=[(datetime.date(2025, 10, 22), datetime.date(2025, 10, 22)), (datetime.date(2025, 10, 23), datetime.date(2025, 10, 23)), (datetime.date(2025, 10, 24), datetime.date(2025, 10, 24)), (datetime.date(2025, 10, 25), datetime.date(2025, 10, 25))], default=datetime.date(2025, 10, 22), verbose_name='Choose Shipment Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('np', 'Not Paid'), ('pr', 'Preparing'), ('se', 'Sent'), ('de', 'Delivered'), ('ca', 'Canceled'), ('rt', 'Returned')], default='np', max_length=2, verbose_name='Order Status'),
        ),
    ]
