# Generated by Django 5.2 on 2025-10-18 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_date_shipment_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_shipment',
        ),
        migrations.AddField(
            model_name='order',
            name='date_receive',
            field=models.DateField(choices=[(datetime.date(2025, 10, 22), datetime.date(2025, 10, 22)), (datetime.date(2025, 10, 23), datetime.date(2025, 10, 23)), (datetime.date(2025, 10, 24), datetime.date(2025, 10, 24)), (datetime.date(2025, 10, 25), datetime.date(2025, 10, 25))], default=datetime.date(2025, 10, 22), verbose_name='Choose Receive Date'),
        ),
    ]
