# Generated by Django 5.2 on 2025-10-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_date_shipment_order_date_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Phone Number(IR)'),
        ),
    ]
