# Generated by Django 5.2 on 2025-10-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("author", models.CharField(max_length=100)),
                ("author_email", models.EmailField(max_length=254)),
                (
                    "stars",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "بی کیفیت"),
                            (2, "بد"),
                            (3, "متوسط"),
                            (4, "خوب"),
                            (5, "عالی"),
                        ],
                    ),
                ),
                (
                    "recommendation",
                    models.BooleanField(
                        choices=[
                            (True, "این محصول را پیشنهاد می کنم"),
                            (True, "این محصول را پیشنهاد نمی کنم"),
                        ],
                        default=True,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
