# Generated by Django 5.2 on 2025-10-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="stars",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "بی کیفیت"),
                    (2, "بد"),
                    (3, "متوسط"),
                    (4, "خوب"),
                    (5, "عالی"),
                ]
            ),
        ),
    ]
