# Generated by Django 5.2 on 2025-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_comment_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_email",
            field=models.EmailField(max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="recommendation",
            field=models.BooleanField(
                choices=[
                    (True, "این محصول را پیشنهاد می کنم"),
                    (True, "این محصول را پیشنهاد نمی کنم"),
                ],
                default=True,
                verbose_name="پیشنهاد به دیگران",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="stars",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "بی کیفیت"),
                    (2, "بد"),
                    (3, "متوسط"),
                    (4, "خوب"),
                    (5, "عالی"),
                ],
                verbose_name="امتیاز",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="متن نظر شما"),
        ),
    ]
