# Generated by Django 5.2 on 2025-10-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_comment_author_alter_comment_author_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="recommendation",
            field=models.BooleanField(
                choices=[
                    (True, "این محصول را پیشنهاد می کنم"),
                    (False, "این محصول را پیشنهاد نمی کنم"),
                ],
                default=True,
                verbose_name="پیشنهاد به دیگران",
            ),
        ),
    ]
