# Generated by Django 5.2 on 2025-10-14 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_cover_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, upload_to='product/covers/', verbose_name='Product Cover'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 14, 8, 6, 50, 833040, tzinfo=datetime.timezone.utc)),
        ),
    ]
