# Generated by Django 5.2 on 2025-10-14 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 14, 16, 46, 32, 866401, tzinfo=datetime.timezone.utc), verbose_name='Date Time'),
        ),
    ]
