# Generated by Django 5.2 on 2025-10-15 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 15, 13, 36, 21, 151802, tzinfo=datetime.timezone.utc), verbose_name='Date Time'),
        ),
    ]
